name: Deploy Production

on:
  push:
    branches:
      - "feature/dogs-horses"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: eu-south-1
          role-to-assume: arn:aws:iam::557438788968:role/GitHubActions
          role-session-name: GitHubActions

      - name: Dependencies install
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: aws s3 sync out/ s3://pg-gaming/