name: Verify

on:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pnpm
      - run: ./node_modules/eslint/bin/eslint.js "{src,apps,libs,test}/**/*.ts" --no-ignore

  dependencies:
    name: Dependencies Analisys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pnpm audit --groups dependencies

  sast:
    name: SAST Analisys
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_RULES: p/default
